"""rename confidence_interval column to avg_confidence in interval_results

Revision ID: 2491a531b839
Revises: c4ff77f1b50c
Create Date: 2025-12-03 17:41:19.417516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2491a531b839'
down_revision: Union[str, None] = 'c4ff77f1b50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_results', sa.Column('avg_confidence', sa.Float(), nullable=True))
    op.drop_column('interval_results', 'confidence_interval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_results', sa.Column('confidence_interval', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_column('interval_results', 'avg_confidence')
    # ### end Alembic commands ###
