"""Add post_title column

Revision ID: 85bdb7e2bfb1
Revises: c0aa1773c5c7
Create Date: 2025-10-08 19:05:52.392297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bdb7e2bfb1'
down_revision: Union[str, None] = 'c0aa1773c5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_jobs', sa.Column('post_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_jobs', 'post_title')
    # ### end Alembic commands ###
