"""Add IsScheduled to MonitoringJobDB

Revision ID: a1b0d055b152
Revises: e05e04a91532
Create Date: 2025-12-02 20:52:02.158848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b0d055b152'
down_revision: Union[str, None] = 'e05e04a91532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_jobs', sa.Column('is_scheduled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_jobs', 'is_scheduled')
    # ### end Alembic commands ###
