"""Initial schema

Revision ID: c0aa1773c5c7
Revises: 
Create Date: 2025-10-08 19:02:32.892856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0aa1773c5c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('intervals_seconds', sa.Float(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('interval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('confidence_interval', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('raw_comments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['monitoring_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interval_results')
    op.drop_table('monitoring_jobs')
    # ### end Alembic commands ###
