"""add user_full_name column to monitoring_jobs table

Revision ID: c4ff77f1b50c
Revises: a1b0d055b152
Create Date: 2025-12-03 04:39:40.237331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ff77f1b50c'
down_revision: Union[str, None] = 'a1b0d055b152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_jobs', sa.Column('user_full_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_jobs', 'user_full_name')
    # ### end Alembic commands ###
