"""Add last_fetched_at to monitoring_jobs

Revision ID: e05e04a91532
Revises: 85bdb7e2bfb1
Create Date: 2025-10-10 13:35:15.944165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05e04a91532'
down_revision: Union[str, None] = '85bdb7e2bfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_jobs', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_jobs', 'last_fetched_at')
    # ### end Alembic commands ###
